In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/lena-bmp/lenna.bmp


In [2]:
import cv2 as cv

img = cv.imread('/kaggle/input/lena-bmp/lenna.bmp')
print(img)

[[[141 141 141]
  [142 142 142]
  [141 141 141]
  ...
  [151 151 151]
  [135 135 135]
  [108 108 108]]

 [[142 142 142]
  [142 142 142]
  [141 141 141]
  ...
  [151 151 151]
  [135 135 135]
  [108 108 108]]

 [[142 142 142]
  [142 142 142]
  [141 141 141]
  ...
  [150 150 150]
  [135 135 135]
  [108 108 108]]

 ...

 [[ 32  32  32]
  [ 31  31  31]
  [ 36  36  36]
  ...
  [ 84  84  84]
  [ 82  82  82]
  [ 82  82  82]]

 [[ 32  32  32]
  [ 32  32  32]
  [ 40  40  40]
  ...
  [ 85  85  85]
  [ 86  86  86]
  [ 90  90  90]]

 [[ 32  32  32]
  [ 32  32  32]
  [ 39  39  39]
  ...
  [ 85  85  85]
  [ 87  87  87]
  [ 90  90  90]]]


In [3]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


/kaggle/input/lena-bmp/lenna.bmp
